### ISSUE TITLE
Missing return statement in relaxed_adjacency_distance?

### ISSUE THREAD

**Issue by italankin** [entangledloops/slidingpuzzle#2]
In `relaxed_adjacency_distance` function, it seems like `return` statement is missing after `swap_tiles`:

https://github.com/entangledloops/slidingpuzzle/blob/2366668b2edcd6605c34235065096c4f244192db/src/slidingpuzzle/heuristics.py#L500-L505

In current version of the function the first misplaced tile is swapped with blank tile, and then any other misplaced tiles are swapped with tiles at **old** blank tile position. I don't see any potential profit in doing this, also the function name states that we should swap only `first` misplaced tile.

So I think the code should look like this:

```python
    def swap_first_misplaced(blank_yx: tuple[int, int]) -> None:
        for y in range(h):
            for x in range(w):
                if get_goal_yx(h, w, board[y][x]) != (y, x):
                    swap_tiles(board, (y, x), blank_yx)
                    return # swap only first misplaced tile
```

I did a rough testing and the "fixed" version generates less nodes, thus expanding and visiting less nodes than current one, but still yielding solutions of the same quality.

Please correct me if I am mistaken and the code is fine.

**Comment by entangledloops** [comment]
Hi @italankin,

Thanks for your thoughtful post. 
I looked it over and you are correct, this is a bug.
I've pushed a correction (and another unrelated bugfix) here:

https://github.com/entangledloops/slidingpuzzle/commit/09c62cfdc27e4009408b1cea6801479822c2a227
